### ISSUE TITLE
Can't establish connection

### ISSUE THREAD

**Issue by sfc-gh-obielov** [snowflakedb/qgis-snowflake-connector#13]
Reported by @cmhh
I tried to install this but it wasn't listed in the plugin repository. I downloaded the zip and tried to install that, but it failed and then reported 'ModuleNotFoundError: No module named 'snowflake''. It's possible that the snowflake connector failed to install because of my proxy, but I haven't looked into it yet.

Edit: actually, I wonder if it's a write access issue installing modules. It seems modules are installed in
`C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages`, and I don't have access there. I'll try and figure out how to install somewhere else.

Edit: okay, it seems modules are installed to `%AppData%` okay, but there was no attempt to install snowflake. I manually installed it using python3 -m pip install --user snowflake. The plugin now seems to be installed, but any attempt to use it still fails with the error `'ModuleNotFoundError: No module named 'snowflake''`. I guess QGIS doesn't automatically search `%AppData%` for plugins.

Update:
I managed to install this plugin. I had to manually install the snowflake module and then restart QGIS. But when I attempt to add a snowflake connection I don't end up with anything usable. I have added a connection using SSO, but the connection form does not provide anywhere for me to enter a role or a schema. I am told my connection is successful, but there's no tree of schemas or tables or anything I can select from.

**Comment by alucinette** [comment]
Hello !
I have the same issue today when I tried connection. 
I haven't the Snowflake library, so I add it manualy with pip. But now, when I click on "Connect", my connection is successful but no data in the tree.
Thanks in advance.
Regards

**Comment by cmhh** [comment]
> @alucinette, @cmhh could you please try [v.0.8.1](https://github.com/snowflakedb/qgis-snowflake-connector/releases/tag/v.0.8.1) and let me know if the issue still exists?

I tried version 0.8.2 and the form does now include a 'role' field, and I successfully connected.  Thanks!

**Comment by sfc-gh-obielov** [comment]
Nice, thanks for confirmation. Closing the issue
