### ISSUE TITLE
Azure AD / Entra ID SSO Login or Login with private certificate not working yet?

### ISSUE THREAD

**Issue by Davidswinkels** [snowflakedb/qgis-snowflake-connector#23]
Hey Snowflake (Oleksii and Erick),

Thanks for developing connection plugin from QGIS to Snowflake! Unfortunately, I could not authenticate from QGIS to Snowflake yet.

**OS and version:** Windows 10 Enterprise
**QGIS version:** 3.28.3-Firenze
**Snowflake environment:** the Snowflake environment of the company is only reachable via private network, and prefers login via Azure AD or with private key.
**Reproduction steps:** connect with SSO or Default authentication in New Snowflake Connection in QGIS
**Error message:**
Connection failed - Check settings and try again.

**Extended error information:**
250003: 250003: Failed to get the response. Hanging? method: post, url: https://<company_name>.west-europe.snowflakecomputing.com:443/session/authenticator-request?request_guid=32a782ee-7863-45d7-a507-f84765225486

<img width="282" alt="image" src="https://github.com/user-attachments/assets/4ee17720-1b62-4fec-b72f-237090a2a402">

Will look into coding the authentication bit myself and make a pull request in the coming 3/4 weeks. We already use this code normally to connect with Python to Snowflake.
```
p_key= serialization.load_pem_private_key(
            bytes(connection_details['PRIVATE_KEY'],'utf8'),
            password=connection_details['PRIVATE_KEY_PWD'].encode(),
            backend=default_backend()
        )

        pkb = p_key.private_bytes(
            encoding=serialization.Encoding.DER,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption())

        db_con = snowflake.connector.connect(
            user=connection_details['USER'],
            account=connection_details['ACCOUNT'],
            private_key=pkb,
            warehouse=connection_details['WAREHOUSE'],
            database=database
            )
```

**Comment by Davidswinkels** [comment]
If I only use the locator that I see, then I get this error message:
<img width="240" alt="image" src="https://github.com/user-attachments/assets/8036db57-779c-4430-9762-fbeff30dc9cf">

Connection failed - Check settings and try again.

Extended error information:
250003 (08001): None: 404 Not Found: post https://<company_name>.snowflakecomputing.com:443/session/authenticator-request?request_guid=0b41be24-cac0-4988-bdcc-d802c8da8097

**Comment by Davidswinkels** [comment]
With help from Oleksii find out the right account setting. Thanks! We had to specify: <company_name>.west-europe.azure in account box. So this issue is solved :)

**Comment by sfc-gh-obielov** [comment]
Thanks @Davidswinkels I updated documentation to reflect the Azure case.
