### ISSUE TITLE
Max QGIS version is out of date

### ISSUE THREAD

**Issue by MichaelGordon** [snowflakedb/qgis-snowflake-connector#40]
Hi 

It's great to see a connector from Snowflake to QGIS! 

I've noticed that the Max QGIS version in the QGIS plugin repository is listed as 3.34.99 (https://plugins.qgis.org/plugins/qgis-snowflake-connector/#plugin-versions) which is several QGIS versions ago and prevents easy installation on latest QGIS versions.

Is this intended?

Thanks,
Michael

**Comment by sfc-gh-obielov** [comment]
@MichaelGordon we support the latest long term release, which is 3.34. We plan to add support for the newer versions in the next months.

**Comment by sfc-gh-obielov** [comment]
@MichaelGordon We updated the qgisMaximumVersion to 3.99. Please try installing it with version 3.40 and let me know if you encounter any issues.

**Comment by MichaelGordon** [comment]
@sfc-gh-obielov That's great, thanks so much! No issues encountered :)

**Comment by MichaelGordon** [comment]
@sfc-gh-obielov That's great, thanks so much! No issues encountered :)

**Comment by MichaelGordon** [comment]
@sfc-gh-obielov That's great, thanks so much! No issues encountered :)
